name: Build

on: push

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-18.04, windows-latest, macos-latest] # skip windows 
        os: [ubuntu-20.04, macos-11]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1


      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.1.1

      - name: Build wheels
        env:
          CIBW_SKIP: "pp* *-manylinux_i686"
          CIBW_BEFORE_BUILD_LINUX: "/bin/bash cibuild/linux_steps.sh"
          CIBW_BEFORE_BUILD_MACOS: "/bin/bash cibuild/macos_steps.sh"
          CIBW_TEST_COMMAND: "cd {project}/pyosmium && rm -rf build && pytest test"
          CIBW_TEST_REQUIRES: pytest shapely

        run: |
          python -m cibuildwheel --output-dir wheelhouse pyosmium

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
